import { GeneratedTrack, NoteData, TonalityName } from '../types';

export interface ComparisonLogInput {
    seed: number;
    styleName: string;
    track: GeneratedTrack;
    engineName?: string;
}

interface MelodyStats {
    count: number;
    pitchLo: number;
    pitchHi: number;
    density: number;
    stepPct: number;
    leapPct: number;
}

function computeMelodyStats(notes: NoteData[], beats: number): MelodyStats {
    if (notes.length === 0 || beats <= 0) {
        return { count: 0, pitchLo: 0, pitchHi: 0, density: 0, stepPct: 0, leapPct: 0 };
    }
    const sorted = notes.slice().sort((a, b) => {
        if (Math.abs(a.onset - b.onset) > 1e-6) return a.onset - b.onset;
        return a.pitch - b.pitch;
    });
    let lo = sorted[0].pitch;
    let hi = sorted[0].pitch;
    for (let i = 1; i < sorted.length; i++) {
        if (sorted[i].pitch < lo) lo = sorted[i].pitch;
        if (sorted[i].pitch > hi) hi = sorted[i].pitch;
    }
    let stepCount = 0;
    let leapCount = 0;
    let total = 0;
    for (let i = 1; i < sorted.length; i++) {
        const iv = Math.abs(sorted[i].pitch - sorted[i - 1].pitch);
        total++;
        if (iv <= 2) stepCount++;
        else if (iv >= 5) leapCount++;
    }
    const stepPct = total > 0 ? Math.round((100 * stepCount) / total) : 0;
    const leapPct = total > 0 ? Math.round((100 * leapCount) / total) : 0;
    return {
        count: sorted.length,
        pitchLo: lo,
        pitchHi: hi,
        density: sorted.length / beats,
        stepPct,
        leapPct,
    };
}

function pad(str: string, width: number): string {
    if (str.length >= width) return str;
    return str + ' '.repeat(width - str.length);
}

function padLeft(str: string, width: number): string {
    if (str.length >= width) return str;
    return ' '.repeat(width - str.length) + str;
}

export function buildComparisonLog(input: ComparisonLogInput): string {
    const { seed, styleName, track } = input;
    const engineName = input.engineName ?? 'AuraFlow';

    const beatsPerBar = track.timeSignature[0];
    const totalBeats = track.sections.length > 0
        ? track.sections[track.sections.length - 1].endBeat
        : 0;

    const keyStr = `${track.key} ${TonalityName[track.tonality] ?? 'Unknown'}`;
    const timeSigStr = `${track.timeSignature[0]}/${track.timeSignature[1]}`;

    const melodyCount = track.melody.length;
    const chordCount = track.chords.length;
    const vocalCount = track.vocal?.length ?? 0;

    const lines: string[] = [];
    lines.push('╔══════════════════════════════════════════════════════════╗');
    lines.push(`║ 🎵 SONG COMPARISON LOG — ${engineName} [${styleName}]`);
    lines.push('╚══════════════════════════════════════════════════════════╝');
    lines.push(
        `META: seed=${seed} key=${keyStr} tempo=${Math.round(track.bpm)} timeSig=${timeSigStr} beats=${totalBeats}`,
    );
    lines.push(
        `TRACKS: melody=${melodyCount} chord=${chordCount} bass=0 drums=0 counter=0 secondary=0 vocal=${vocalCount}`,
    );
    lines.push('(bass/drums/counter/secondary are generated by Orchestrator — not captured at raw-generation stage)');
    lines.push('');

    lines.push('STRUCTURE (name, bars, beats, energy)');
    for (const section of track.sections) {
        const secBeats = section.endBeat - section.startBeat;
        const secBars = beatsPerBar > 0 ? secBeats / beatsPerBar : 0;
        lines.push(
            `  ${pad(section.name, 16)} bars=${padLeft(secBars.toFixed(0), 4)}  beats=${padLeft(secBeats.toFixed(0), 5)}  E=${section.energyLevel}`,
        );
    }
    lines.push('');

    lines.push('MELODY STATS (name, count, midi_range, density_n_per_beat, step%/leap%)');
    for (const section of track.sections) {
        const secNotes = track.melody.filter(
            (n) => n.onset + 1e-6 >= section.startBeat && n.onset < section.endBeat - 1e-6,
        );
        const secBeats = section.endBeat - section.startBeat;
        const stats = computeMelodyStats(secNotes, secBeats);
        lines.push(
            `  ${pad(section.name, 16)} count=${padLeft(String(stats.count), 3)}  range=${stats.pitchLo}-${stats.pitchHi}  dens=${stats.density.toFixed(2)}  step=${stats.stepPct}%/leap=${stats.leapPct}%`,
        );
    }
    lines.push('');

    lines.push('HARMONY (name, chord progression)');
    for (const section of track.sections) {
        const secChords = track.chords.filter(
            (c) => c.startBeat + 1e-6 >= section.startBeat && c.startBeat < section.endBeat - 1e-6,
        );
        const numerals = secChords.map((c) => c.numeral).join(' ');
        lines.push(`  ${pad(section.name, 16)} ${numerals}`);
    }
    lines.push('══════════════════════════════════════════════════════════');

    return lines.join('\n');
}
