#!/usr/bin/env python3
"""
Phase 4.2 — Golden Seed JSON → C 头文件转换工具

读取 golden-seed-output.json，输出 C 可 #include 的验证数据。
用法：python3 scripts/json2c.py [input.json] [output.h]

默认：scripts/golden-seed-output.json → scripts/golden_seed_data.h
"""

import json
import sys
from pathlib import Path

def main():
    script_dir = Path(__file__).parent
    input_path = Path(sys.argv[1]) if len(sys.argv) > 1 else script_dir / "golden-seed-output.json"
    output_path = Path(sys.argv[2]) if len(sys.argv) > 2 else script_dir / "golden_seed_data.h"

    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    seeds = data["seeds"]
    ppq = data["ppq"]
    style_count = data["styleCount"]

    lines = []
    lines.append("/**")
    lines.append(" * Auto-generated by scripts/json2c.py")
    lines.append(f" * Source: {input_path.name}")
    lines.append(f" * Generated: {data['generatedAt']}")
    lines.append(f" * PRNG: {data['prngAlgorithm']}")
    lines.append(" *")
    lines.append(" * DO NOT EDIT — regenerate with: python3 scripts/json2c.py")
    lines.append(" */")
    lines.append("")
    lines.append("#ifndef GOLDEN_SEED_DATA_H")
    lines.append("#define GOLDEN_SEED_DATA_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")

    # Constants
    lines.append(f"#define GOLDEN_SEED_COUNT       {len(seeds)}")
    lines.append(f"#define GOLDEN_PPQ              {ppq}")
    lines.append(f"#define GOLDEN_STYLE_COUNT      {style_count}")
    lines.append("")

    # Available style IDs
    style_ids = [s["id"] for s in data["availableStyles"]]
    lines.append(f"static const uint8_t GOLDEN_STYLE_IDS[{len(style_ids)}] = {{")
    lines.append(f"    {', '.join(str(s) for s in style_ids)}")
    lines.append("};")
    lines.append("")

    # PRNG snapshot struct
    lines.append("typedef struct {")
    lines.append("    uint32_t seed;")
    lines.append("    uint32_t stateA;          /* after setSeed */")
    lines.append("    uint8_t  selectedStyleId;")
    lines.append("    uint32_t stateB;          /* after style selection */")
    lines.append("    uint32_t stateC;          /* after generateFullSong */")
    lines.append("    uint32_t stateD;          /* after arrange */")
    lines.append("} GoldenPRNGSnapshot;")
    lines.append("")

    # PRNG snapshots array
    lines.append(f"static const GoldenPRNGSnapshot GOLDEN_PRNG[{len(seeds)}] = {{")
    for i, s in enumerate(seeds):
        comma = "," if i < len(seeds) - 1 else ""
        lines.append(f"    {{ /* seed={s['seed']} */")
        lines.append(f"        .seed = {s['seed']}u,")
        lines.append(f"        .stateA = {s['stateA']}u,")
        lines.append(f"        .selectedStyleId = {s['selectedStyleId']},")
        lines.append(f"        .stateB = {s['stateB']}u,")
        lines.append(f"        .stateC = {s['stateC']}u,")
        lines.append(f"        .stateD = {s['stateD']}u")
        lines.append(f"    }}{comma}")
    lines.append("};")
    lines.append("")

    # Track metadata struct
    lines.append("typedef struct {")
    lines.append("    uint32_t seed;")
    lines.append("    uint16_t bpm;")
    lines.append("    uint8_t  keyOffset;       /* 0~11 */")
    lines.append("    uint8_t  tonality;")
    lines.append("    uint8_t  timeSigNum;")
    lines.append("    uint8_t  timeSigDen;")
    lines.append("    uint16_t sectionCount;")
    lines.append("    uint16_t melodyNoteCount;")
    lines.append("    uint16_t chordCount;")
    lines.append("} GoldenTrackMeta;")
    lines.append("")

    lines.append(f"static const GoldenTrackMeta GOLDEN_TRACK[{len(seeds)}] = {{")
    for i, s in enumerate(seeds):
        t = s["track"]
        comma = "," if i < len(seeds) - 1 else ""
        lines.append(f"    {{ /* seed={s['seed']} */")
        lines.append(f"        .seed = {s['seed']}u,")
        lines.append(f"        .bpm = {t['bpm']},")
        lines.append(f"        .keyOffset = {t['keyOffset']},")
        lines.append(f"        .tonality = {t['tonality']},")
        lines.append(f"        .timeSigNum = {t['timeSignature'][0]},")
        lines.append(f"        .timeSigDen = {t['timeSignature'][1]},")
        lines.append(f"        .sectionCount = {t['sectionCount']},")
        lines.append(f"        .melodyNoteCount = {t['melodyNoteCount']},")
        lines.append(f"        .chordCount = {t['chordCount']}")
        lines.append(f"    }}{comma}")
    lines.append("};")
    lines.append("")

    # Arranged track counts struct
    lines.append("typedef struct {")
    lines.append("    uint32_t seed;")
    lines.append("    uint16_t melodyCount;")
    lines.append("    uint16_t pianoLHCount;")
    lines.append("    uint16_t pianoRHCount;")
    lines.append("    uint16_t drumsCount;")
    lines.append("    uint16_t secondaryMelodyCount;")
    lines.append("    uint16_t counterMelodyCount;")
    lines.append("    uint16_t vocalCount;")
    lines.append("} GoldenArrangedCounts;")
    lines.append("")

    lines.append(f"static const GoldenArrangedCounts GOLDEN_ARRANGED[{len(seeds)}] = {{")
    for i, s in enumerate(seeds):
        a = s["arranged"]
        comma = "," if i < len(seeds) - 1 else ""
        lines.append(f"    {{ /* seed={s['seed']} */")
        lines.append(f"        .seed = {s['seed']}u,")
        lines.append(f"        .melodyCount = {a['melodyNoteCount']},")
        lines.append(f"        .pianoLHCount = {a['pianoLHNoteCount']},")
        lines.append(f"        .pianoRHCount = {a['pianoRHNoteCount']},")
        lines.append(f"        .drumsCount = {a['drumsNoteCount']},")
        lines.append(f"        .secondaryMelodyCount = {a['secondaryMelodyNoteCount']},")
        lines.append(f"        .counterMelodyCount = {a['counterMelodyNoteCount']},")
        lines.append(f"        .vocalCount = {a['vocalNoteCount']}")
        lines.append(f"    }}{comma}")
    lines.append("};")
    lines.append("")

    # MIDI event summary struct
    lines.append("typedef struct {")
    lines.append("    uint32_t seed;")
    lines.append("    uint32_t totalCount;")
    lines.append("    uint32_t noteOnCount;")
    lines.append("    uint32_t noteOffCount;")
    lines.append("    uint32_t ccCount;")
    lines.append("    const char *sha256;       /* hex string */")
    lines.append("} GoldenMidiSummary;")
    lines.append("")

    # SHA-256 string literals
    for s in seeds:
        lines.append(f'static const char GOLDEN_SHA256_SEED_{s["seed"]}[] = "{s["midiEvents"]["sha256"]}";')
    lines.append("")

    lines.append(f"static const GoldenMidiSummary GOLDEN_MIDI[{len(seeds)}] = {{")
    for i, s in enumerate(seeds):
        m = s["midiEvents"]
        comma = "," if i < len(seeds) - 1 else ""
        lines.append(f"    {{ /* seed={s['seed']} */")
        lines.append(f"        .seed = {s['seed']}u,")
        lines.append(f"        .totalCount = {m['totalCount']}u,")
        lines.append(f"        .noteOnCount = {m['noteOnCount']}u,")
        lines.append(f"        .noteOffCount = {m['noteOffCount']}u,")
        lines.append(f"        .ccCount = {m['ccCount']}u,")
        lines.append(f"        .sha256 = GOLDEN_SHA256_SEED_{s['seed']}")
        lines.append(f"    }}{comma}")
    lines.append("};")
    lines.append("")

    # First 10 MIDI events per seed (for spot-checking)
    lines.append("typedef struct {")
    lines.append("    int32_t  ticks;")
    lines.append("    uint8_t  type;            /* 0=noteOn,1=noteOff,2=cc,3=programChange,4=pitchBend,5=visual */")
    lines.append("    uint8_t  channel;")
    lines.append("    uint8_t  data1;")
    lines.append("    uint8_t  data2;")
    lines.append("} GoldenMidiEvent;")
    lines.append("")

    type_map = {
        "noteOn": 0, "noteOff": 1, "cc": 2,
        "programChange": 3, "pitchBend": 4, "visual": 5
    }

    for s in seeds:
        seed = s["seed"]
        events = s["midiEvents"]["first10Events"]
        lines.append(f"static const GoldenMidiEvent GOLDEN_FIRST10_SEED_{seed}[{len(events)}] = {{")
        for j, e in enumerate(events):
            comma = "," if j < len(events) - 1 else ""
            t = type_map.get(e["type"], 5)
            lines.append(f"    {{ {e['ticks']}, {t}, {e['channel']}, {e['data1']}, {e['data2']} }}{comma}")
        lines.append("};")
        lines.append("")

    lines.append("#endif /* GOLDEN_SEED_DATA_H */")
    lines.append("")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Generated: {output_path}")
    print(f"  {len(seeds)} seeds, {sum(1 for l in lines if l.strip())} non-empty lines")


if __name__ == "__main__":
    main()
